### ISSUE TITLE
Startup errors and broken basic functions

### ISSUE THREAD

**Issue by rnett** [cbeust/kash#6]
Windows 10, started from git bash.

kotlinc is installed.

Basic shell features (e.g. `ls`) work.

```
$ ./kash-debug
Jun 07, 2019 8:52:36 AM org.jline.utils.Log logr
WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
WARN: Failed to initialize native filesystem for Windows
java.lang.RuntimeException: Could not find installation home path. Please make sure bin/idea.properties is present in the installation directory.
        at org.jetbrains.kotlin.com.intellij.openapi.application.PathManager.getHomePath(PathManager.java:90)
        at org.jetbrains.kotlin.com.intellij.openapi.application.PathManager.getHomePath(PathManager.java:68)
        at org.jetbrains.kotlin.com.intellij.openapi.application.PathManager.findBinFile(PathManager.java:171)
        at org.jetbrains.kotlin.com.intellij.util.lang.UrlClassLoader.loadPlatformLibrary(UrlClassLoader.java:338)
        at org.jetbrains.kotlin.com.intellij.openapi.util.io.win32.IdeaWin32.<clinit>(IdeaWin32.java:48)
        at org.jetbrains.kotlin.com.intellij.openapi.util.io.FileSystemUtil.getMediator(FileSystemUtil.java:62)
        at org.jetbrains.kotlin.com.intellij.openapi.util.io.FileSystemUtil.<clinit>(FileSystemUtil.java:54)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandler.setFileAttributes(ZipHandler.java:62)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandler$1.createAccessor(ZipHandler.java:44)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandler$1.createAccessor(ZipHandler.java:39)
        at org.jetbrains.kotlin.com.intellij.util.io.FileAccessorCache.createHandle(FileAccessorCache.java:61)
        at org.jetbrains.kotlin.com.intellij.util.io.FileAccessorCache.get(FileAccessorCache.java:54)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandler.getCachedZipFileHandle(ZipHandler.java:84)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandler.acquireZipHandle(ZipHandler.java:131)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ZipHandlerBase.createEntriesMap(ZipHandlerBase.java:44)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.ArchiveHandler.getEntriesMap(ArchiveHandler.java:197)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.jar.CoreJarHandler.<init>(CoreJarHandler.java:42)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.jar.CoreJarFileSystem.lambda$new$0(CoreJarFileSystem.java:33)
        at org.jetbrains.kotlin.com.intellij.util.containers.ConcurrentFactoryMap$2.create(ConcurrentFactoryMap.java:181)
        at org.jetbrains.kotlin.com.intellij.util.containers.ConcurrentFactoryMap.get(ConcurrentFactoryMap.java:45)
        at org.jetbrains.kotlin.com.intellij.openapi.vfs.impl.jar.CoreJarFileSystem.findFileByPath(CoreJarFileSystem.java:44)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.findJarRoot(KotlinCoreEnvironment.kt:365)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.contentRootToVirtualFile(KotlinCoreEnvironment.kt:344)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.access$contentRootToVirtualFile(KotlinCoreEnvironment.kt:123)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$3.invoke(KotlinCoreEnvironment.kt:222)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$3.invoke(KotlinCoreEnvironment.kt:123)
        at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.convertClasspathRoots(ClasspathRootsResolver.kt:70)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:229)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:123)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:413)
        at org.jetbrains.kotlin.cli.jvm.repl.GenericReplChecker.<init>(GenericReplChecker.kt:63)
        at org.jetbrains.kotlin.cli.jvm.repl.GenericReplCompiler.<init>(GenericReplCompiler.kt:53)
        at org.jetbrains.kotlin.cli.jvm.repl.GenericReplCompiler.<init>(GenericReplCompiler.kt:51)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine$replCompiler$2.invoke(KotlinJsr223JvmLocalScriptEngine.kt:47)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine$replCompiler$2.invoke(KotlinJsr223JvmLocalScriptEngine.kt:38)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine.getReplCompiler(KotlinJsr223JvmLocalScriptEngine.kt)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine$localEvaluator$2.invoke(KotlinJsr223JvmLocalScriptEngine.kt:53)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine$localEvaluator$2.invoke(KotlinJsr223JvmLocalScriptEngine.kt:38)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine.getLocalEvaluator(KotlinJsr223JvmLocalScriptEngine.kt)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine.getReplEvaluator(KotlinJsr223JvmLocalScriptEngine.kt:55)
        at org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngine.createState(KotlinJsr223JvmLocalScriptEngine.kt:59)
        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.createState$default(KotlinJsr223JvmScriptEngineBase.kt:46)
        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.getCurrentState(KotlinJsr223JvmScriptEngineBase.kt:53)
        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.nextCodeLine(KotlinJsr223JvmScriptEngineBase.kt:44)
        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compileAndEval(KotlinJsr223JvmScriptEngineBase.kt:59)
        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.eval(KotlinJsr223JvmScriptEngineBase.kt:33)
        at java.scripting/javax.script.AbstractScriptEngine.eval(Unknown Source)
        at com.beust.kash.Shell.<init>(Shell.kt:58)
        at com.beust.kash.Main.run(Main.kt:16)
        at com.beust.kash.MainKt.main(Main.kt:7)
[main] DEBUG com.beust.kash.Shell - Read kts/Predef.kts
[main] DEBUG com.beust.kash.Shell - Type(Kotlin), Exec:SingleCommand(exec=Exec([Word("[myPrompt]"), RightParenthesis(c=))]))
Desktop/kash [master]$ fun test() = "test"
fun test()[main] DEBUG com.beust.kash.Shell - Type(Kotlin), Exec:SingleCommand(exec=Exec([Word("[fun]"), Word("[test]"), RightParenthesis(c=)), Word("[=]"), Word(""[test]"")]))
[main] DEBUG com.beust.kash.Shell - Type(Kotlin), Exec:SingleCommand(exec=Exec([Word("[myPrompt]"), RightParenthesis(c=))]))
Desktop/kash [master]$ test()
test()[main] DEBUG com.beust.kash.Shell - Type(Command), Exec:SingleCommand(exec=Exec([Word("[test]"), RightParenthesis(c=))]))
[main] DEBUG com.beust.kash.Shell - Launching C:\Program Files\Git\usr\bin\test.exe
[main] DEBUG com.beust.kash.Shell - Type(Kotlin), Exec:SingleCommand(exec=Exec([Word("[myPrompt]"), RightParenthesis(c=))]))
Desktop/kash [master]$
```

**Comment by cbeust** [comment]
The errors are coming from Kotlin itself, I see them sporadically and I'm not quite sure how to fix them. They reference a missing file in the installation directory...

The second problem is probably due to the fact that `test` is also a command on your path, can you verify?  Try `which test`. I have it on my own path.

When Kotlin determines it is a command, it runs it as a command instead of Kotlin code, hence what you are seeing.

There are a couple more issues with your report though, looking into them and keeping this open.

**Comment by rnett** [comment]
Yeah, `test` is on my path from Git.  

Imo, it would be nice if calling it with parentheses would call the Kotlin version, as `test()`, or if there was a way to force it to (I tried backticks, didn't do it).

**Comment by Pozo** [comment]
According to the `RuntimeException` I've found [this thread](https://github.com/arturbosch/detekt/pull/634) which might be useful. Since I'm not a windows user I can't try it out.

**Comment by cbeust** [comment]
> Imo, it would be nice if calling it with parentheses would call the Kotlin version, as test(), or if there was a way to force it to (I tried backticks, didn't do it).

That's exactly the fix I'm writing :-)

**Comment by cbeust** [comment]
I actually found a function that does that, `setIdeaIoUseFallback()`. It seems to start without the error now, can you update and try again?

**Comment by rnett** [comment]
Yup, that fixes it.

Not sure if its related, but commands are echoed on each line before the output.

E.g. (with Git Bash as the parent terminal)
```
Desktop/kash [master]$ fun mytest() = "test"
fun mytest()Desktop/kash [master]$ mytest()
mytest()test
Desktop/kash [master]$
```

**Comment by cbeust** [comment]
I see that in the IDEA console window too and I traced it to jline. I think it happens when `\r` is not properly handled: jline sends an `\r` and rewrites the line, but in your window (and IDEA's), it's interpreted as a newline and printed on the next line.

I don't see this in a few other different Windows shells, and not on MacOS either.

OS fragmentation :-(

I was hoping jline would abstract me from that though.
